name: "invictus"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=invictus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: "./backend"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_NAME=invictus_db
      - FLASK_APP=app.main
      - SECRET_KEY=148924jfq3f21rfh
      - JWT_SECRET_KEY=akf228934mokf21
  frontend:
    build: "./frontend"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
