"""Reinicio BD con nuevos campos + bugs corregidos

Revision ID: 046aa63eba73
Revises: 
Create Date: 2026-03-14 18:51:50.454804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046aa63eba73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_api', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('dificultad', sa.String(length=50), nullable=False),
    sa.Column('instrucciones', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('maquina', sa.String(length=50), nullable=True),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_api')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'normal', name='tipousuario'), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('dias', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tener',
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ),
    sa.PrimaryKeyConstraint('rutina_id', 'ejercicio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tener')
    op.drop_table('rutina')
    op.drop_table('usuario')
    op.drop_table('ejercicio')
    # ### end Alembic commands ###
