"""add foto_url to usuarios

Revision ID: 82cba0d6d3d1
Revises: f11d9c38569e
Create Date: 2026-05-22 16:04:52.487416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cba0d6d3d1'
down_revision = 'f11d9c38569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
