"""añadir columna orden

Revision ID: 9b97b52f4f57
Revises: 82cba0d6d3d1
Create Date: 2026-05-23 17:14:58.032884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b97b52f4f57'
down_revision = '82cba0d6d3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tener', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
