"""añadir columna peso

Revision ID: 9ce3e837fee4
Revises: 046aa63eba73
Create Date: 2026-03-22 10:44:25.414707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce3e837fee4'
down_revision = '046aa63eba73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tener', schema=None) as batch_op:
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
